### PR TITLE
fix: shell startup script error with arguments fixed

### LINKED ISSUE #2522: The sshnpd.sh script fails to translate the required arguments when using TMUX or CRON
### Describe the bug

When using the universal installer and targeting CRON or TMUX the "" around the arguments are interpreted by the shell and the sshnpd is passed arguments that it cannot make sense of.

The issue is nuanced as echoing the command line that is parsed looks just fine, but the shell interprets the delegate_policy=""  and then "$delegate_policy" as an empty process argument and the sshnpd errors out. Equally if you put in "-p (at)cconstab" that gets parsed as one argument to the process and  not two so sshnpd gives a weird error too.

### Steps to reproduce

1. First install in the normal way but on a machine/container that does not have systemd 
2. see the sshnpd not running
3. run the sshnpd.sh by hand and scratch your head for a while

### Expected behavior

The script should run with TMUX/CRON installs..

### PR DESCRIPTION
**Pull request by cconstab**
**- What I did**
fixed issue with staruop scripts
**- How I did it**
moved to conditional statements 
**- How to verify it**
tested locally and with new install
**- Description for the changelog**

shell startuo scripts error with arguments fixed

### CODE REVIEW

File: packages/dart/sshnoports/bundles/shell/headless/srvd.sh [hunk 1]
```diff
@@ -10,7 +10,9 @@ v="-v"              # Comment to disable verbose logging
 
 sleep 10 # allow machine to bring up network
 export USER="$user"
-while true; do
-	"$binary_path"/srvd -a "$atsign" -i "$internet_address" "$v"
-	sleep 10
+    set -- -a "$atsign"
```
Comment (cpswan) [inline packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: What's the thinking around removing the keep alive loop?

Comment (gkc) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: +1

Comment (cconstab) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: Good catch.. I edited the copy of this file in the build dir until I noticed that is all .gitnored (doh) I obviously messed up with the cut/paste

Comment (cpswan) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: Is there another commit inbound to put it back?

Comment (cconstab) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: I thoughtbis there already ?

Comment (cconstab) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: 9c5a98ac6c25ab03d3451be5a1a2bb9344f8fedd

File: packages/dart/sshnoports/bundles/shell/headless/srvd.sh [hunk 2]
```diff
@@ -9,6 +9,7 @@ v="-v"              # Comment to disable verbose logging
 # END METADATA
 
 sleep 10 # allow machine to bring up network
+while true; do
 export USER="$user"
```
Comment (gkc) [inline packages/dart/sshnoports/bundles/shell/headless/srvd.sh:12]: Plz move the export to before the while loop

File: packages/dart/sshnoports/bundles/shell/headless/srvd.sh (hunk 1 above)
Comment (gkc) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:14]: it is

**Review by gkc — CHANGES_REQUESTED** [review]

**Review by cconstab — COMMENTED** [review]
added this while

File: packages/dart/sshnoports/bundles/shell/headless/srvd.sh (hunk 2 above)
Comment (cconstab) [reply packages/dart/sshnoports/bundles/shell/headless/srvd.sh:12]: will do

**Review by cpswan — APPROVED** [review]

**Review by cpswan — APPROVED** [review]

**Review by gkc — APPROVED** [review]
