### PR TITLE
fix: empty session and tunnel username are treated as null.

### LINKED ISSUE #712: Empty Session and Tunnel Username prevents a successful ssh in the desktop app
### Describe the bug

SSH Fails if the session or tunnel username is empty. Empty strings should be treated as null.

### Steps to reproduce

1. First I created a profile without that does not require a session username
2. Then I tried to ssh and it failed

### Expected behavior

A profile that does not require a session username should not fail to ssh when a session username is not provided.

### Screenshots

_No response_

### Smartphones

- Device: M1 Mac
- OS: MacOS

- Version: 14.1.1

### Were you using an atApplication when the bug was found?

SSH No Ports Desktop

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CurtlyCritchlow**
**- What I did**

- Replaces empty string as null when using the session and tunnel username.
- Added additional validation to SR Address, Device address, remote sshd port and local forwarding port.

**- How I did it**

**- How to verify it**

1. Run the app
2.  edit or create a profile. 
3. enter an invalid value in the form field

**- Description for the changelog**

Improve validation when creating profiles and empty session and tunnel username are treated as null.

### CODE REVIEW

File: packages/dart/sshnp_flutter/lib/src/utility/form_validator.dart [hunk 1]
```diff
@@ -10,12 +10,23 @@ class FormValidator {
...
+  static String? validateRequiredIntField(String? value) {
+    String valid = r'^[0-9]+$';
+    if (value?.isEmpty ?? true) {
+      return kEmptyFieldValidationError;
+    } else if (!RegExp(valid).hasMatch(value!)) {
+      return kIntFieldValidationError;
+    }
+    return null;
+  }
+
```
Comment (xavierchanth) [inline packages/dart/sshnp_flutter/lib/src/utility/form_validator.dart:24]: Specifically for ports, we can do one better, and say the range is 0-65535

Comment (CurtlyCritchlow) [reply packages/dart/sshnp_flutter/lib/src/utility/form_validator.dart:24]: done

**Review by xavierchanth — APPROVED** [review]

**Comment by xavierchanth** [comment]
Nice work @CurtlyCritchlow
