### PR TITLE
fix: profiles are refreshed when first sync after onboarding is completed

### LINKED ISSUE #754: Make sure the dashboard page reloads to show the profiles after initial sync

### PR DESCRIPTION
**Pull request by CurtlyCritchlow**
…eted

**- What I did**
    Fixes #754 
    Clear KeyChain the first time the app is run
**- How I did it**
   Add a progress listener that refreshes the profiles controller when sync is completed, this is only done after onboarding when the user is on the Home Screen.
**- How to verify it**

1. Run the app, 
2. Onboard 
3. A snackbar will be show stating if sync failed, in progress or completed

**- Description for the changelog**

Profiles are refreshed when the first sync after onboarding is completed

### CODE REVIEW

File: packages/dart/sshnp_flutter/lib/src/utility/my_sync_progress_listener.dart [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    if (isSyncStatusSuccess && isCurrentRouteHome && isFirstRun) {
+      await ref.read(configListController.notifier).refresh();
+      CustomSnackBar.notification(content: 'Sync Completed');
+      await AuthenticationRepository().setFirstRun(false);
+      log('Initial Sync completed');
+    } else if (isSyncStatusFailure && isCurrentRouteHome && isFirstRun) {
+      await ref.read(configListController.notifier).refresh();
+      CustomSnackBar.notification(content: 'Sync failed... Retrying');
+
+      log('Initial Sync failed');
```
Comment (xavierchanth) [inline packages/dart/sshnp_flutter/lib/src/utility/my_sync_progress_listener.dart:39]: @CurtlyCritchlow maybe we should implement a counter to stop trying after 3 tries or something

**Review by xavierchanth — APPROVED** [review]

File: packages/dart/sshnp_flutter/lib/src/utility/my_sync_progress_listener.dart (hunk 1 above)
Comment (CurtlyCritchlow) [reply packages/dart/sshnp_flutter/lib/src/utility/my_sync_progress_listener.dart:39]: We want it to keep retrying but the snackbar should only be show once. I'll make the update.

Comment (xavierchanth) [reply packages/dart/sshnp_flutter/lib/src/utility/my_sync_progress_listener.dart:39]: Okay, if you think it's fine as is
