### PR TITLE
fix: have desktop app emit notifications with same namespaces as the np_admin service does

### LINKED ISSUE #2281: policy service not (in real time) picking up changes made via noports desktop
### Describe the bug

- When I make a change via the np_admin web app, changes are picked up in near-real-time by the policy service
- But when I make a change via the desktop app, changes are not picked up by the policy service

### Steps to reproduce

.

### Expected behavior

Policy change notifications should be sent by the desktop app in the same way as by the web app

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
- Fixes https://github.com/atsign-foundation/noports/issues/2281
- fix: have desktop app emit notifications with same namespaces as the np_admin service does

**- How I did it**
fix: in npt_flutter: use `namespaceAware: false` for the notifications which are sent when a policy rule is added / updated / deleted

**- How to verify it**
- Have manually verified
- np_admin emits notifications like: `@policy:1.groups.policy.sshnp@policy`
- desktop used to emit notifications like: `@policy:1.groups.policy.sshnp.noports@policy`
- Now desktop emits notifications like `@policy:1.groups.policy.sshnp@policy`

### CODE REVIEW

File: packages/dart/noports_core/lib/src/admin/impl.dart [hunk 1]
```diff
@@ -22,17 +22,17 @@ class PolicyServiceWithAtClient extends PolicyServiceInMem
     atClient.notificationService
         .subscribe(regex: r'.*\.groups\.policy\.sshnp', shouldDecrypt: true)
         .listen((AtNotification n) {
```
Comment (gkc) [inline packages/dart/noports_core/lib/src/admin/impl.dart:24]: No actual changes in this file, just formatting and logging

File: packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart [hunk 2]
```diff
@@ -94,9 +94,14 @@ class RoleRepository {
 
       if (success) {
         try {
+          AtKey notifKey = AtKey.fromString('$currentAtSign:$atKeyStr');
+          notifKey.metadata.namespaceAware = false;
```
Comment (gkc) [inline packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart:98]: ^^ that's the thing

File: packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart [hunk 3]
```diff
@@ -151,9 +156,14 @@ class RoleRepository {
...
```
Comment (gkc) [inline packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart:160]: ^^

File: packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart [hunk 4]
```diff
@@ -202,9 +212,14 @@ class RoleRepository {
       );
       if (success) {
         try {
+          AtKey notifKey = AtKey.fromString('$currentAtSign:$atKeyStr');
+          notifKey.metadata.namespaceAware = false;
```
Comment (gkc) [inline packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart:216]: ^^

File: packages/dart/npt_flutter/pubspec.lock [hunk 5]
```diff
@@ -175,10 +175,10 @@ packages:
     description:
       path: "packages/at_onboarding_flutter"
       ref: at_onboarding_flutter_layers
-      resolved-ref: "1e244eb5f522d31d9d0eb3c67990d7d6bd612446"
+      resolved-ref: f7f022a2d4b145f4d8b35c07f5a5cb2085551d86
       url: "https://github.com/atsign-foundation/at_widgets"
     source: git
-    version: "6.1.10"
+    version: "6.1.10+20251107"
```
Comment (gkc) [inline packages/dart/npt_flutter/pubspec.lock:181]: Pick up [this fix](https://github.com/atsign-foundation/at_widgets/pull/1005)

**Comment by gkc** [comment]
FIxes #2281

**Review by cpswan — APPROVED** [review]
