### PR TITLE
fix: sshnpd main process leaks

### LINKED ISSUE #1716: test: testing of c sshnpd to ensure it is ready for 1.0
- testing of c sshnpd in a variety of scenarios to ensure that it is memory resilient
- more e2e tests if we think we need them
- possibly add a functional/unit test suite

### PR DESCRIPTION
**Pull request by xavierchanth**
closes #1716 

**- What I did**

- Updated tooling (just commands) to help analyze and address leaks
- Addressed leaked strings in handler commons, ssh request handler, npt request handler
- Refactored cleanup on child processes, but awaiting: https://github.com/Mbed-TLS/mbedtls/issues/9958
  - We don't need this though to address all leaks in the main process, which are fully handled in this PR

**- How I did it**

**- How to verify it**

See valgrind logs here: https://gist.github.com/XavierChanth/3636f55f625f14c8999b1bed43916eae
Note: A handful of these logs will show leaks, but that is when a child process from an srv session is closed, the logs indicate process number like `==PID==` on the left margin, lowest number is the main process.

**- Description for the changelog**
fix: sshnpd main process leaks

### CODE REVIEW

File: packages/c/sshnpd/src/handle_npt_request.c [hunk 1]
```diff
@@ -33,7 +33,11 @@ void handle_npt_request(atclient *atclient, pthread_mutex_t *atclient_lock, sshn
   // allocated: envelope
 
   // log envelope
-  atlogger_log(LOGGER_TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "Received envelope: %s\n", cJSON_Print(envelope));
+  if (atlogger_get_logging_level() >= ATLOGGER_LOGGING_LEVEL_DEBUG) {
+    char *envelope_str = cJSON_Print(envelope);
+    atlogger_log(LOGGER_TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "Received envelope: %s\n", envelope_str);
+    free(envelope_str);
+  }
```
Comment (xavierchanth) [inline packages/c/sshnpd/src/handle_npt_request.c:40]: Pre check if the logger will even print the json before attempting to serialize it. Also, free it.

File: packages/c/sshnpd/src/handler_commons.c [hunk 2]
```diff
@@ -581,7 +583,14 @@ int send_success_payload(cJSON *payload, atclient *atclient, pthread_mutex_t *at
     atlogger_log(LOGGER_TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "Released the atclient lock\n");
   }
 
-clean_res: { free(keyname); }
+clean_notify:
+  atclient_notify_params_free(&notify_params);
+clean_res: {
+  if (final_res_atkey_str != NULL) {
+    free(final_res_atkey_str);
+  }
```
Comment (xavierchanth) [inline packages/c/sshnpd/src/handler_commons.c:591]: `notify_params` & `final_res_atkey_str` both weren't freed, hence the refactors above to also help address it.

File: packages/c/valgrind-test-scenarios.md [hunk 3]
```diff
@@ -0,0 +1,61 @@
+# Valgrind Test Scenarios
```
Comment (xavierchanth) [inline packages/c/valgrind-test-scenarios.md:1]: These test scenarios map to the valgrind logs I posted under `how to verify it`

**Review by cpswan — APPROVED** [review]
