### PR TITLE
fix: onboarding now works on windows and switch atSign feature updated.

### LINKED ISSUE #1908: Backup Key prompt is shown for atsign already backed up.
### Describe the bug

Sometimes the backup key is shown for atsigns that are not in teapot state.

### Steps to reproduce

1. Onboard with an old atsign from noPortsDesktop v 1.2.0
2. You may be prompted to back up you key even though you have done so already.

### Expected behavior

Only atisgn in teapot state should be prompted to back up their keys.

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### LINKED ISSUE #1909: User is shown that profile failed to load
### Describe the bug

User is shown settings profile failed to load on the settings screen.

### Steps to reproduce

1. Navigate to the settings screen of NoPorts Desktop with a new atsign.
4.

### Expected behavior

While this behaviour is expected when the default profile is being shown, no warnings should be shown on the UI

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### LINKED ISSUE #1927: Windows Desktop App - Unable to onboard
### Describe the bug

This issue is only present in the windows version of the desktop app and is presenting slightly differently in the store version vs the current test version.

**Store Version**
When attempting to onboard, the app shows "preparing for activation" and displays the loader indefinitely. This happens when trying:
- an invalid atSign
- a brand new atSign
- an atSign that has been activated on another machine and is ready for enrollment
I was not able to try an atSign that successfully onboarded but signed out because it was on a brand new VM

**Test Version**
- When attempting to onboard, the app says the atSign does not exist in this root domain. This happens when trying:
- a brand new atSign
- an atSign that has been activated on another machine and is ready for enrollment
- an invalid atSign (expected behavior)
If you have an atSign that was previously onboarded and the keys are saved on that machine, and you sign out, it onboards successfully.

Neither of these issue are present in the macOS versions of the app.

### Steps to reproduce

Download the app and attempt to activate a new atSign or an atSign that was activated on a different machine

### Expected behavior

We should be able to successfully onboard 

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CurtlyCritchlow**
**- What I did**
- Change client atSign to NoPorts atSign.
- Corrected the NoPorts logo.
- ensure tray_manager  window manager settings are applied after frame callback and only on macOS where applicable.
- Updated switch atSign functionality.

closes #1908
closes #1909 
**- How I did it**

**- How to verify it**
Run the app.
**- Description for the changelog**

### CODE REVIEW

File: packages/dart/npt_flutter/lib/features/onboarding/widgets/onboarding_button.dart [hunk 1]
```diff
@@ -282,6 +281,8 @@ class _OnboardingButtonState extends State<OnboardingButton> {
               atClientPreference: atClientPrefernce,
             ),
           );
+          // If the user used APKAM, we do not have to back up the keys after onboarding
+          App.navState.currentContext!.read<BackupKeyCubit>().setBackupKeyStatus(true);
```
Comment (xavierchanth) [inline packages/dart/npt_flutter/lib/features/onboarding/widgets/onboarding_button.dart:285]: We shouldn't tell the user to backup at all for onboard, not just apkam. If they used a file to activate the app then they don't need to backup another copy of the same file they just used and thus already have a backup of.

Only need to force a backup for newly activated atSigns

**Review by xavierchanth — CHANGES_REQUESTED** [review]
See my comment above

File: packages/dart/npt_flutter/lib/features/onboarding/widgets/onboarding_button.dart (hunk 1 above)
Comment (CurtlyCritchlow) [reply packages/dart/npt_flutter/lib/features/onboarding/widgets/onboarding_button.dart:285]: I reviewed my code. it is consistent with what you want. In teapot we set to false (show dialog to backup atKeys) in APKAM or atKeys upload we set to true (don't show dialog). if atsign already in key chain do nothing since the default state is true (don't show dialog).

**Review by xavierchanth — APPROVED** [review]
