### PR TITLE
fix: policy cache on edit/save

### LINKED ISSUE #2285: Policy info in-app cache is not updated when you 'save' a role update
### Describe the bug

Policy info in-app cache is not updated when you 'save' a role update

### Steps to reproduce

1. I update a rule and hit save
2. If I then select the rule again, it shows the old info
3. But if I hit refresh, and then select the rule again, it shows the correct info

### Expected behavior

Shouldn't need to refresh

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
closes #2285 

**- What I did**
- Fixed Policy form so you don't have to refresh to get the latest data

**- How I did it**
Using Claude

- Policy cubit has new `reloadAndSelectRole` function which is meant to be used in onSuccess.
- When editing an existing role, `reloadAndSelectRole` is called on the existing role's id
- When creating a new role, `putNewRole` is called and returns the roleId so that when a new role is created, we can call `reloadAndSelectRole` to select that newly created role.
- When we delete a role, no role is selected in the main view

**- How to verify it**
Cases that were tested

1. Editing an existing role
2. Creating a new role
3. Deleting a role

In the first two cases, they will go to the current role and have updated cache.
In third case, no role will be selected

**- Description for the changelog**
fix: policy cache on edit/save

### CODE REVIEW

File: packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart [hunk 1]
```diff
@@ -112,10 +112,10 @@ class RoleRepository {
           );
         }
       }
-      return success;
+      return success ? newId.toString() : null;
```
Comment (JeremyTubongbanua) [inline packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart:115]: This is what `newId` is

```dart
final int maxId = await getMaxGroupId();
final int newId = maxId + 1;
```

Comment (JeremyTubongbanua) [reply packages/dart/npt_flutter/lib/features/policy/repositories/role_repository.dart:115]:
```dart
Future<int> getMaxGroupId() async {
    final List<FetchedRole> roles = await fetchRoles();
    if (roles.isEmpty) return 0;

    int maxId = 0;
    for (final role in roles) {
      final parsedId = int.tryParse(role.id) ?? 0;
      if (parsedId > maxId) {
        maxId = parsedId;
      }
    }
    return maxId;
}
```

**Review by gkc — APPROVED** [review]
Works perfectly. LGTM
