### PR TITLE
fix: the rest of universal installer

### LINKED ISSUE #906: universal.sh / multibuild changes required for 5.1.0 release
What I have done:

- laid the foundation for universal.sh script
- updated the multibuild action to update the bound release version for universal.sh and export as an artifact when doing a tagged build
- Added npt to install.sh (the more manual installer)
- Modified the install.sh and bundles to prepare for universal.sh 

What needs doing:
- [x] create a new branch off of trunk
- [x] change the sshnp_version metadata in universal.sh to match the prerelease containing the new bundle format ("5.1.0-rc.5")
- [x] run universal.sh to test and iterate; known issues:
  - [ ] some variables are used when unset in certain flows, you may need to change them from `unset foo` to `foo=''`
    - This is done to ensure we are intentional about the state of variables in the script
  - [x] unarchiving on linux is running into blockers
  - [x] can't assume ~/.local/bin exists
  - [x] can't assume ~/.local/bin is on PATH
  - [x] need to copy binaries to where they'll be run from
  - [x] need to copy template for systemd unit
  - [x] need to copy template for tmux/headless script
  - [x] on linux we assume systemd if we have root access, we should also make sure systemd is installed before trying to use it
- [ ] Add npt to the codesign list in multibuild

### PR DESCRIPTION
**Pull request by xavierchanth**
fixed #906 
closes #912 

**- What I did**

- Fixed the launchd installation
- Changed the artifact name in multibuild so it is unique across builds
- Added an extra print statement for clarity to the magic script
- cleaned up remaining bugs and input stuff in universal.sh

**- How I did it**

**- How to verify it**

If you get stuck please run with -v and send me the logs.
I will sort out the rest from there.
 
Places tested:

- [x] @xavierchanth's m1 macbook (client, device, both)
- [x] Ubuntu 22.04 VM (client, device, both) - using interactive prompts
- [x] Ubuntu 22.04 VM (client, device, both) - using command line flags
- [x] AL2023 VM (device) - using interactive prompts
- [x] AL2023 VM (device) - using command line flags

v5.1.0-rc.11 tests (with macbook fixes & new multi atkeys selector for @gkc):
- [x] m1 macbook - (device - many atkeys files available)
- [x] m1 macbook - (device - single atkeys file available)
- [x] Ubuntu 22.04 - (device - 2 atkeys files)
- [x] Ubuntu 22.04 - (device - 1 atkeys files)

**- Description for the changelog**
fix: the rest of universal installer

### CODE REVIEW

**Comment by gkc** [comment]
@XavierChanth 

Fails immediately for me on MacOS
```
gary@gkc2019-2 ~ % ./universal.sh -v
+ shift
+ '[' 0 -gt 0 ']'
+ '[' true = true ']'
+ print_env
+ echo Environment:
Environment:
+ echo 'Platform Name: macos'
Platform Name: macos
+ echo 'System Arch: arm64'
System Arch: arm64
+ echo 'Temporary Path: /tmp'
Temporary Path: /tmp
+ echo 'As Root: false'
As Root: false
+ echo 'Binary Path: /Users/gary/.local/bin'
Binary Path: /Users/gary/.local/bin
+ echo 'User: gary'
User: gary
+ '[' -n '' ']'
++ get_download_url
++ unset download_urls
+++ grep browser_download_url
++++ norm_version 5.1.0-rc.6
+++ cut '-d"' -f4
+++++ echo 5.1.0-rc.6
+++++ sed -e 's/"//g' -e 's/^tags\///g' -e 's/^v//g'
++++ version=tags/v5.1.0-rc.6
++++ echo tags/v5.1.0-rc.6
+++ curl -fsSL https://api.github.com/repos/atsign-foundation/noports/releases/tags/v5.1.0-rc.6
++ download_urls='https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-riscv64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-x64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-windows-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/universal.sh'
++ '[' -z 'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-riscv64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-x64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-windows-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/universal.sh' ']'
++ echo 'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-arm64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-riscv64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-x64.tgz
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-windows-x64.zip
https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/universal.sh'
++ grep macos
++ grep arm64
++ cut '-d"' -f4
+ download_url='https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip'
+ echo 'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip'
+ download_archive
+ read -r download_url
+ echo 'Downloading archive from https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip'
Downloading archive from https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip
+ curl -sL 'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip' -o /tmp/sshnp-1711716526.zip
+ cleanup
+ rm -f /tmp/sshnp-1711716526.zip
+ rm -rf /tmp/sshnp-1711716526
gary@gkc2019-2 ~ % echo $?
3
```

curl exit code 3 is malformed URL which is weird because if I copy and paste that precise command as echoed above into a terminal it works fine
```
gary@gkc2019-2 ~ % curl -sL 'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip' -o /tmp/sshnp-1711716526.zip

gary@gkc2019-2 ~ % echo $?
0
```

I suspect that the single quotes are the problem here. So for example
```
gary@gkc2019-2 ~ % curl -sL "'https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-macos-arm64.zip'" -o /tmp/sshnp-1711716526.zip

gary@gkc2019-2 ~ % echo $?
3

```

**Comment by gkc** [comment]
Testing on Ubuntu, client installation. Looks good except that the binaries aren't available where they should be

```
ubuntu@gkcrvd:~$ ./universal.sh
Downloading archive from https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-x64.tgz
Install type (device, client, both): 
$ client
Enter client atSign:
$ alice
Enter device atSign:
$ bob
Pick your default region:
  am   : Americas
  ap   : Asia Pacific
  eu   : Europe
  @___ : Specify a custom region atSign
$ eu
Installing a quick picker script to make it easy to connect to devices...
Enter the device names you would like to include in the quick picker script
/done to finish
$ test_universal
$ foo
$ /done
ubuntu@gkcrvd:~$ cat .local/bin/@sshnp
#!/bin/bash
# SCRIPT METADATA
binary_path="$HOME/.local/bin"
client_atsign="@alice"
device_atsign="@bob"
host_atsign="@rv_eu"
devices=( test_universal foo)
additional_args=()
# END METADATA

unset d
echo "Select a device (enter the number):"
select d in "${devices[@]}"; do
	break
done

if [ -z "$d" ]; then
	echo "No device selected"
	exit 1
fi

"$binary_path"/sshnp -f "$client_atsign" -t "$device_atsign" -h "$host_atsign" -d "$d" "${additional_args[@]}" "$@"
ubuntu@gkcrvd:~$ .local/bin/@sshnp
Select a device (enter the number):
1) test_universal
2) foo
#? 2
.local/bin/@sshnp: line 22: /home/ubuntu/.local/bin/sshnp: No such file or directory
ubuntu@gkcrvd:~$ ls -trl .local/bin
total 4
-rwxr-xr-x 1 ubuntu ubuntu 463 Mar 29 13:03 @sshnp
ubuntu@gkcrvd:~$ 
```

**Comment by gkc** [comment]
Testing on Ubuntu, device installation. Same problem as with client installation - while the binaries have been downloaded and unpacked, they haven't been copied to ~/.local/bin

```
ubuntu@gkcrvd:~$ ./universal.sh
Downloading archive from https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.6/sshnp-linux-x64.tgz
Install type (device, client, both): 
$ device
Enter client atSign:
$ alice
Enter device atSign:
$ bob
Enter device name:
$ test_universal
sed: can't read /home/ubuntu/.local/bin/sshnpd.sh: No such file or directory
ubuntu@gkcrvd:~$ 
```

File: packages/dart/sshnoports/bundles/universal.sh [hunk 1]
```diff
@@ -79,12 +85,28 @@ usage() {
 	fi
```
Comment (cpswan) [inline packages/dart/sshnoports/bundles/universal.sh]: @XavierChanth should this be `universal.sh` rather than `install.sh`?

**Comment by cpswan** [comment]
Testing a device install on Ubuntu. `install.sh` is being called, but doesn't seem to be doing anything.

e.g. this can be seen in verbose logging:

```
/tmp/sshnp-1712051112/sshnp/install.sh -b /home/ubuntu/.local/bin -u ubuntu tmux sshnpd
```

but ~/.local/bin remains empty

It's the same if I run:

```
/tmp/sshnp-1712051112/sshnp/install.sh -b /home/ubuntu/.local/bin sshnpd
```

I've already done `mkdir -p ~/.local/bin` to ensure the target directory is there (it isn't by default on a cloud-init VM).

**Comment by cpswan** [comment]
Running just:

```
/tmp/sshnp-1712051112/sshnp/install.sh sshnpd
```

Works just fine :)

```
=> Installed sshnpd to /home/ubuntu/.local/bin
```

Looks like the problem is with option handing:

```
	case "$1" in
	--help | '')
		usage
		exit 0
		;;
	-b)
		binary_dir="$1"
		shift
		;;
```

1. This will set `binary_dir` to `-b` as that's what $1 is that we just tested for 🤦 
2. If we use $2 then at least `binary_dir` gets set correctly
3. But... we then pass through the rest of the `case` statement and exit with nothing happening, because the `shift` doesn't cause things to be re-evaluated.

File: packages/dart/sshnoports/bundles/universal.sh (hunk 1 above)
Comment (xavierchanth) [reply packages/dart/sshnoports/bundles/universal.sh]: Good catch, yes it should

**Comment by xavierchanth** [comment]
Thanks @cpswan, I'll do an rc.7 release
edit: rc.8

**Comment by cpswan** [comment]
rc9 worked on my Ubuntu test VM for a device install :)

But... there's no mention of keys, so I think we should be testing for the presence of keys and alerting the user to put them in place.

Also the installer should say (at least a little bit) about what it's done (along similar lines to what install.sh says) e.g.:

```
tumx sshnp has been installed into /home/ubuntu/.local/bin
an entry has been added to the crontab which will take effect on reboot
run now with:
tmux new-session -d -s sshnpd && tmux send-keys -t sshnpd /home/ubuntu/.local/bin/sshnpd.sh C-m
you can connect to the daemon script with:
tmux attach -t sshnpd
and disconnect with:
Crtl-b d
```

**Comment by cpswan** [comment]
rc9 failed on my AL2023 test VM:

```
/tmp/sshnp-1712076095/sshnp/install.sh: line 326: crontab: command not found
```

**Comment by xavierchanth** [comment]
> rc9 failed on my AL2023 test VM:
> 
> ```
> /tmp/sshnp-1712076095/sshnp/install.sh: line 326: crontab: command not found
> ```

I literally can't trust anything to be consistently available across the industry anymore...

**Comment by xavierchanth** [comment]
Nice... industry moving to systemd as the one size fits all solution, when some things can't/ don't run systemd... cron is the one thing that is usually consistently available to schedule tasks directly under init.d
CleanShot 2024-04-02 at 12 00 18

Nothing wrong with systemd, I think it's great, but especially in recent times, this is frustrating. (Also amazon linux just doesn't play nice in general, I have had to do some much extra work just to support them)

**Comment by cpswan** [comment]
@XavierChanth I'm using AL2023 to test as it's probably the thorniest of ELs and so if we can get it working there, we can reasonably expect things to work in other EL flavours

If we're going to lean on systemd (which I think is wise given its prevalence in mainstream distros) then the installer needs to be nudging folk in that direction.

Where there's no systemd (or no sudo to install to it) we need to be checking that other tools are available and suggesting how to install them. This sadly descends into a rats nest of conditionals pretty quickly :(

We're somewhat back to the tribulations of the dess installer :/

More fun... no tmux either in default AL2023

**Comment by cpswan** [comment]
Just tested a systemd install on my AL2023 VM. It's not working, and if I look in /etc/systemd/system/sshnpd.service the User= field hasn't been replaced:

```
# MANDATORY: User to run the daemon as
User=<username>
```

If I manually update it things work OK. So need to patch up the script to do the replacement.

**Comment by xavierchanth** [comment]
> More fun... no tmux either in default AL2023

I never expect tmux to be available by default. but I do expect cron and nohup, which is what our headless one depends on. Guess we will need to check for that... thankfully AL2023 has systemd which means we should use that. if you run universal.sh as root (i.e. with sudo) it should automatically use systemd... maybe we should check if systemd is installed and nudge them down the systemd route with a few y/n prompts?

To be clear, I also only kept the headless version around because it was the one true fallback that would just work on any system. I actually think it is a terrible way to install sshnpd, so if it can't be the one true fallback then I think we should get rid of it to simplify things.

**Comment by cpswan** [comment]
@XavierChanth I think this is ready to be merged. I've done a bunch more testing on both Ubuntu and AL2023 for both client and device installs using the guided prompts and command line options.

**Comment by xavierchanth** [comment]
> @XavierChanth I think this is ready to be merged. I've done a bunch more testing on both Ubuntu and AL2023 for both client and device installs using the guided prompts and command line options.

I wasn't able to reproduce @gkc 's install issues, let me confirm with him first.

**Comment by gkc** [comment]
We figured out what the problems were (1) my grep options which included --color=always and (2) missing function mac_only

File: packages/dart/sshnoports/bundles/universal.sh [hunk 2]
```diff
@@ -35,435 +42,667 @@ device_atsign=""
...
+        echo "Selected: @$selectedatsign"
+      else
+        echo "No existing atkeys were selected"
+      fi
+    fi
+  else
+    mkdir -p "$user_home"/.atsign/keys
+    echo "$HOME/.atsign/keys directory created"
+  fi
+}
```
Comment (xavierchanth) [inline packages/dart/sshnoports/bundles/universal.sh]: I modified this function so that it only asks y/n if a single key was found.
Otherwise it presents a numerical options list to choose from with 0/empty being don't select anything, and numbers 1+ being the various atkeys to choose from

**Comment by xavierchanth** [comment]
@gkc can I get one last sanity test against: https://github.com/atsign-foundation/noports/releases/download/v5.1.0-rc.11/universal.sh

I will prepare the v5.1.0 release

**Comment by xavierchanth** [comment]
https://github.com/atsign-foundation/noports/releases/tag/v5.1.0

**Comment by xavierchanth** [comment]
I cheated and am rebuilding universal.sh for v5.1.0 on commit https://github.com/atsign-foundation/noports/pull/913/commits/d3498627d9d07998ee5bb5c1bf7b6460a7e68c36 (also installs at_activate now)

The rest of v5.1.0 is built on https://github.com/atsign-foundation/noports/pull/913/commits/4cac6783d8b27b9aeae99ba6ebce9d0cd92db441

**Review by cpswan — DISMISSED** [review]

**Review by gkc — APPROVED** [review]

**Review by cpswan — APPROVED** [review]

**Comment by xavierchanth** [comment]
Okay, I will move tag v5.1.0 to https://github.com/atsign-foundation/noports/pull/913/commits/546c59dea5218cf3b4d427d3c9422f2049431735 and rebuild the release.

**Comment by xavierchanth** [comment]
There is a straggler dockerhub build, but that should be unchanged, since we haven't changed anything other than shell scripts since it's last v5.1.0 tagged build
