### PR TITLE
fix: Fixed UI issues in NoPorts Desktop

### LINKED ISSUE #2292: NoPorts Desktop - UI Issues
**Sync in progress toast notification looks strange**
It looks like there might be an icon or something missing on the toast notification displayed when the app is syncing. compare the two screen shots below 
Image
Image

**Random grey box on Set Pin screen**
There is a random get horizontal box on the Set Pin screen, under authenticator.
Image

**Alignment issues on the profile creation screen**
I've added purple lines to show where items are not aligned and blue arrows to show where spaces seem too big
Image

**Can't paste OTP into both the enrollment and the activation OTP screens**
When you try to paste an OTP into these screens nothing happens. 

**Coloring on the Policy Roles difficult to read when selected**
There isn't enough contrast between the background and the text color when a Role is selected.
Image

**The role creation screen is a little crammed**
When creating a role, the screen elements are really close together which makes it difficult to read. It might look better if the items are displayed vertically instead of horizontally.
Image

**Cursor jumps to the end of the word when entering an atSign**
If you enter an atSign, say @tinashe404 and you decide you want to change the 404 to 304, if you move your cursor to the first 4 and press delete/backspace, it starts to delete from the end of the atSign. The same happens if you attempt to type from the middle of the atSign.

**There is no obvious way to leave the profile creation screen**
There is no obvious way to leave the profile creation screen now. A back or cancel button might be helpful here. 
https://github.com/user-attachments/assets/28ceab19-1911-4f4b-a2da-010f47866c0a

**Policy role creation error messages appear in the background**
When creating a role, the add devices and add device group error messages appear in the background. An example is if under Permit Opens, you try to enter something that isn't in the format word:number, it displays an error message for this, but its in the background as shown in the screenshot.
Image

**Error message wont go away**
I clicked on back up key file, then when the file picker appeared I clicked cancel. An error appeared saying it failed to save the keys and it wont go away. Ive switched atSigns, moved to different tabs, clicked on the error message and it wont go away. it was cleared by closing the app and opening it again 
Image

### PR DESCRIPTION
**Pull request by CurtlyCritchlow**
**- What I did**

- Aligned Local port and Remote port correctly.
- Made Info SnackBar prefix text visible.
- Removed when user cancels backing up their key.
- Updated Policy Screen layout for better spacing.
- Standardised widget styles, enhance form validation and improve layout consistency across policy forms.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

File: packages/dart/npt_flutter/lib/features/policy_form/widgets/at_signs_list_widget.dart [hunk 1]
```diff
@@ -27,6 +32,15 @@ class _AtSignsListWidgetState extends State<AtSignsListWidget> {
   late TextEditingController _addController;
   late List<String> _localAtSigns;
   bool _isHovering = false;
+  static const double _itemHeight = Sizes.p42;
+
```
Comment (CurtlyCritchlow) [inline packages/dart/npt_flutter/lib/features/policy_form/widgets/at_signs_list_widget.dart:36]: set a max list height once list is greater than 5 items

**Review by xavierchanth — APPROVED** [review]

**Review by JeremyTubongbanua — APPROVED** [review]
