### PR TITLE
fix: Various tweaks to resolve #1792, #1856, #1864, #1876, #1877

### LINKED ISSUE #1792: add --help to npp_atserver
npp_atserver can't print usage (no args, and --help both only print the error & stack trace).

Some of the other new binaries may also have this issue.

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
fix: Various tweaks to resolve #1792, #1856, #1864, #1876, #1877

**- How I did it**
See files changed

**- How to verify it**
- Automated tests pass, and
- Manual test output provided in comments below. If you wish to try it out, there is a multibuild against this branch [here](https://github.com/atsign-foundation/noports/actions/runs/14759542939)

### CODE REVIEW

**Comment by gkc** [comment]
Manual test output for #1792 
```
gary@gkc2019 sshnoports % sshnp/npp_atserver             
Usage: 
    --help                  Usage instructions
-a, --atsign (mandatory)    atSign of this policy service
-k, --key-file              The atSign's atKeys file if not in ~/.atsign/keys/
-v, --[no-]verbose          More logging

Invalid argument(s): Option atsign is mandatory.


gary@gkc2019 sshnoports % sshnp/npp_atserver --help
    --help                  Usage instructions
-a, --atsign (mandatory)    atSign of this policy service
-k, --key-file              The atSign's atKeys file if not in ~/.atsign/keys/
-v, --[no-]verbose          More logging


gary@gkc2019 sshnoports % sshnp/npp_atserver --foo 
Usage: 
    --help                  Usage instructions
-a, --atsign (mandatory)    atSign of this policy service
-k, --key-file              The atSign's atKeys file if not in ~/.atsign/keys/
-v, --[no-]verbose          More logging

Could not find an option named "foo".
```

**Comment by gkc** [comment]
Manual test output for #1877 
```
gary@gkc2019 build % sshnp/np_admin --help                  
    --help                  Usage instructions
-a, --atsign (mandatory)    The atSign to use
-v, --verbose               More logging
-b, --bind-ip               Bind to something other than the default
                            (defaults to "127.0.0.1")
-p, --bind-port             Bind to something other than the default port
                            (defaults to "3000")


gary@gkc2019 build % sshnp/np_admin       
Usage: 
    --help                  Usage instructions
-a, --atsign (mandatory)    The atSign to use
-v, --verbose               More logging
-b, --bind-ip               Bind to something other than the default
                            (defaults to "127.0.0.1")
-p, --bind-port             Bind to something other than the default port
                            (defaults to "3000")

Option atsign is mandatory.

```



Manual test output for #1856
```
gary@gkc2019 build % sshnp/np_admin -a @garycasey
Will bind to port 3000 on interface 127.0.0.1
Connecting ... Connected
SHOUT|2025-04-30 17:24:13.217671|PolicyServiceWithAtClient|Loading groups via AtClient 
^C


gary@gkc2019 build % sshnp/np_admin -a @garycasey -b 0.0.0.0
Will bind to port 3000 on interface 0.0.0.0
Connecting ... Connected
SHOUT|2025-04-30 17:24:29.603941|PolicyServiceWithAtClient|Loading groups via AtClient 
^C


gary@gkc2019 build % sshnp/np_admin -a @garycasey -b 127.0.0.1 -p 8080
Will bind to port 8080 on interface 127.0.0.1
Connecting ... Connected

```

**Comment by gkc** [comment]
Manual test output for #1864 
```
gary@gkc2019 build % sshnp/npp_atserver -a garycasey
SHOUT|2025-04-30 17:28:48.825379|PolicyServiceWithAtClient|Loading groups via AtClient 
SHOUT|2025-04-30 17:28:50.075711|PolicyServiceWithAtClient|Loading group from atKey: 1.groups.policy.sshnp@garycasey 
[...]
```

File: packages/dart/noports_core/lib/src/npa/npa_params.dart [hunk 1]
```diff
@@ -24,7 +27,7 @@ class NPAParams {
     // Arg check
     ArgResults r = parser.parse(args);
 
-    String authorizerAtsign = r['atsign'];
+    String authorizerAtsign = (r['atsign'] as String).toAtsign();
```
Comment (xavierchanth) [inline packages/dart/noports_core/lib/src/npa/npa_params.dart:30]: The toAtsign() extension I added in at_utils can throw errors, as it is functionally equivalent to the fixAtsign util from before.

**Review by xavierchanth — APPROVED** [review]
My one comment to be aware of, otherwise lgtm

File: packages/dart/noports_core/lib/src/npa/npa_params.dart (hunk 1 above)
Comment (gkc) [reply packages/dart/noports_core/lib/src/npa/npa_params.dart:30]: Thanks Xavier. The call to `NPAParams.fromArgs` is wrapped in its own try-catch block in npp_atserver's `main` function
