### PR TITLE
fix: Only allow single instance of NoPorts Desktop on Windows

### LINKED ISSUE #1680: Unknown Error is shown when the user tries to onboard while having two instance of the app running.
### Describe the bug

When user doesn't close the app from the tray and tries to onboard with a second instance of the app, the get an unknown error snackbar.

### Steps to reproduce

1. Onboard with no port desktop
2. Close the app without closing from the tray.
3. And then try to onboard again.

### Expected behavior

Display an error message telling the user to close the app from the tray and then try again or prevent the app from creating multiple instances.
### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

NoPorts Desktop

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- Launching NoPorts Desktop will focus any existing instances instead of launching a new instance

The existing behavior:

- Launch noports, onboard an atsign
- close window (doesnt' kill current instance)
- launch app again
- **new window**

Desired behavior (that this PR provides):

- Launch noports, onboard an atsign
- close window (doesn't kill current instance)
- launch app again
- **show existing window**

Retained behavior:
- When an atSign _isn't_ onboarded and the window is closed, then it does kill the current instance.

**- How I did it**

**- How to verify it**

**- Description for the changelog**
fix: Only allow single instance of NoPorts Desktop on Windows

### CODE REVIEW

File: packages/dart/npt_flutter/windows/runner/main.cpp [hunk 1]
```diff
@@ -13,21 +15,27 @@ int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
     CreateAndAttachConsole();
   }
 
+  HWND hwnd = ::FindWindow(kWindowClassName, kWindowName);
+  if (hwnd != NULL) {
+    ::ShowWindow(hwnd, SW_NORMAL);
+    ::SetForegroundWindow(hwnd);
+    return EXIT_FAILURE;
+  }
+
```
Comment (xavierchanth) [inline packages/dart/npt_flutter/windows/runner/main.cpp:24]: If we find a window matching the default Flutter window class name && Titled "NoPorts Desktop" open that instead.

File: packages/dart/npt_flutter/windows/runner/win32_window.cpp [hunk 2]
```diff
@@ -11,20 +11,20 @@ namespace {
...
 /// version 10.0.22000.0.
-/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+/// See:
+/// https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
 #ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
 #define DWMWA_USE_IMMERSIVE_DARK_MODE 20
 #endif
 
-constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
-
```
Comment (xavierchanth) [inline packages/dart/npt_flutter/windows/runner/win32_window.cpp:20]: moved this to its .h file so we have access to it in main.cpp too.

**Comment by xavierchanth** [comment]
I rebased [03d23e4](https://github.com/atsign-foundation/noports/pull/1713/commits/03d23e4d5afc2007839697333313885528b86883) back onto trunk since it was based on a wildly divergent branch, then I retested.

**Comment by xavierchanth** [comment]
> I rebased [03d23e4](https://github.com/atsign-foundation/noports/pull/1713/commits/03d23e4d5afc2007839697333313885528b86883) back onto trunk since it was based on a wildly divergent branch, then I retested.

Correction, I am retesting... VSCode cached commits... so they appeared in the build despite the rebase.

**Comment by xavierchanth** [comment]
Okay, ready for review, tested with a git history that matches that of this PR.

**Review by Zambrella — APPROVED** [review]

**Review by cconstab — APPROVED** [review]
Built and tested on windows home and clean build odf windows.. Clicking the toolbar brings up the existing instance not a new one
